### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by rubenwardy** [minetest-mods/smartfs#14]
Creating formspecs using layouts

**Comment by bell07** [comment]
What do you mean in this issue? Something like xml/xsl to split presentation and data?
Or defining the layout using http://dev.minetest.net/Lua_Table_Formspec ?
The layout approach has the disadvantage the hooks / methods needs to be special-handled at other place. I like the smartfs because this split is shut and the Button-pressing-code can be near to the button definition.

**Comment by rubenwardy** [comment]
Rather than manually placing elements, you would use layouts like so:

```lua
local layouter = state:layouter(0, 0, "vertical", 3)  -- x/y/orientation/spacing
layouter:button("name", "Text")
```

although the constructors look a little icky there

**Comment by bell07** [comment]
Nice idea. Size calculation depending on Text length will be tricky. The position depends on other elements (collision detection) too. Reminds me of "html". Maybe some concepts can be applied from other markup language. But it would be better to see such concepts in minetest core not in lua-mods.

**Comment by rubenwardy** [comment]
> But it would be better to see such concepts in minetest core not in lua-mods.

I agree. It's on my to do list

**Comment by bell07** [comment]
Just for reference, maybe far-fetched, but the best UI-framework I know is OpenUI5. The views are defined in XML. The Framework is for HTML5, written in Javascript, cannot applied directly also. But maybe some concepts can be adopt. http://openui5.org/getstarted.html#step3
